<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSAccount</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>100</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5cf35801-bc53-4b3f-90c9-1a3282da0c47</testSuiteGuid>
   <testCaseLink>
      <guid>3ab7121e-2f67-420f-b2ec-761246ac31f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>c041ca7c-40d7-4e86-aec5-2c245bf40b89</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/MyAccount/TCAccountDetails</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a5aa10b9-e0ec-420d-931f-4ea29a3e67ff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a5aa10b9-e0ec-420d-931f-4ea29a3e67ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c041ca7c-40d7-4e86-aec5-2c245bf40b89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a5aa10b9-e0ec-420d-931f-4ea29a3e67ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b8a1dc11-fdc3-472d-ba10-88c1c1c0c2d0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4162c47e-8fb0-4192-9b68-13b6bcbdd0e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyAccount/TCOrders1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>03531022-e043-4269-af9c-c3d349996361</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>03531022-e043-4269-af9c-c3d349996361</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2544af04-7d91-4a0b-8c56-fd86c2ec6f9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>03531022-e043-4269-af9c-c3d349996361</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a5ddc81f-3b4b-42e4-9fd7-c2e9a54dd30b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e0b04a2-7ad0-4c11-af40-967903e8fe92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>4469ed92-531a-4525-a16f-dcecac388052</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/MyAccount/TCorders2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d4935f1-3c04-49c1-b53e-8fb2985a702c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d4935f1-3c04-49c1-b53e-8fb2985a702c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>4469ed92-531a-4525-a16f-dcecac388052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d4935f1-3c04-49c1-b53e-8fb2985a702c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>ea186b5e-5aa1-4c44-8746-129485860d5a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a13e697-f96b-4554-a958-dc04fa302e7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MyAccount/Tcorders3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>00fd373c-3a82-432b-9fdb-52740bf92cea</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>00fd373c-3a82-432b-9fdb-52740bf92cea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>ff93f4ca-456e-4790-b043-93c1f780ff1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>00fd373c-3a82-432b-9fdb-52740bf92cea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>c290ab45-4f56-435b-a0bc-486d679f6348</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
